#!/bin/bash

if [ -z "$1" ]
then
    echo "gavrasm plop.asm"
    exit -1
fi

PLAIN_NAME=$(echo $1 | sed -e 's/.asm$//g')
LOG_FILE="${PLAIN_NAME}.log"
ERROR_FILE="${PLAIN_NAME}.err"

/opt/gavrasm/gavrasm -E -S -M $1 >$LOG_FILE
ERROR_CODE=$?

if [ -f $ERROR_FILE ]
then
    cat $ERROR_FILE
fi

exit $ERROR_CODE
