#!/usr/bin/bash

cd ch340g/libusb_test/
gcc libusb_test.c $(pkg-config libusb-1.0 --libs --cflags) -o libusb_test
if [ $? -eq 0 ]
then
    chmod u+x libusb_test
    sudo chmod ugo+rw $( \
        lsusb -d 1a86:7523 | \
        awk '{ gsub(/:/, ""); print "/dev/bus/usb/" $2 "/" $4 }' \
    )
    ./libusb_test $@
fi
cd ../..
